CREATE TABLE IF NOT EXISTS room_layouts (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  pet_id      INTEGER NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
  layout_json TEXT    NOT NULL DEFAULT '[]',
  updated_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(pet_id)
);
